
package com.example.concurrence.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiServiceService", targetNamespace = "http://controller.api.bms.com/", wsdlLocation = "http://localhost:1010/api/apiService?wsdl")
public class ApiServiceService
    extends Service
{

    private final static URL APISERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException APISERVICESERVICE_EXCEPTION;
    private final static QName APISERVICESERVICE_QNAME = new QName("http://controller.api.bms.com/", "ApiServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1010/api/apiService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APISERVICESERVICE_WSDL_LOCATION = url;
        APISERVICESERVICE_EXCEPTION = e;
    }

    public ApiServiceService() {
        super(__getWsdlLocation(), APISERVICESERVICE_QNAME);
    }

    public ApiServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APISERVICESERVICE_QNAME, features);
    }

    public ApiServiceService(URL wsdlLocation) {
        super(wsdlLocation, APISERVICESERVICE_QNAME);
    }

    public ApiServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APISERVICESERVICE_QNAME, features);
    }

    public ApiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApiService
     */
    @WebEndpoint(name = "ApiServicePort")
    public ApiService getApiServicePort() {
        return super.getPort(new QName("http://controller.api.bms.com/", "ApiServicePort"), ApiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiService
     */
    @WebEndpoint(name = "ApiServicePort")
    public ApiService getApiServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.api.bms.com/", "ApiServicePort"), ApiService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APISERVICESERVICE_EXCEPTION!= null) {
            throw APISERVICESERVICE_EXCEPTION;
        }
        return APISERVICESERVICE_WSDL_LOCATION;
    }

}
